### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [mindstorm12/gather#4]
The overall cleanliness of your code aids in the legibility and efficiency of both organization and structure.
This was one of the better written GatherIV projects I've reviewed and I'm confident that you too can move forward confidently for future projects.

Grade: Meets expectation, wonderful work!

**Comment by mindstorm12** [comment]
Thanks Joseph! Can I close these 'issues' in Github?

**Comment by josephgupkim** [comment]
Yes of course! :)
